version: '3.1'
services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD='3fk0ddqv'