---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname  }}"
    - name: Set timezone
      timezone:
        name: "{{ tmzone }}" 
    - name: Created user "{{ user }}"
      user:
        name: "{{ user }}"
        state: present
        group: sudo
        append: true
        shell: /bin/bash
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - git
    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install docker
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Check docker is active
      service:
        name: docker
        state: started
        enabled: yes
    - name: Check is group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: Adding "{{ user }}" to docker group
      user:
        name: "{{ user }}"
        group: docker
        append: yes
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        owner: "{{ user }}"
        group: docker
    - name: Install ufw firewall
      apt:
        name: ufw
        state: latest
        update_cache: yes
    - name: Enable firewall and deny by default
      ufw:
        state: enabled
        default: deny
    - name: Allow SSH coonections
      ufw:
        rule: allow
        name: OpenSSH
    - name: Allow access to tcp ports 80 and 443
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - '80'
        - '443'
    - name: Create project directory
      file:
        path: /data/db-project
        state: directory
        mode: 0755
        owner: devops
        group: docker      
    - name: Clone Remote Git Repository
      git:
        repo: 'https://github.com/lemberg21/stuff.git'
        dest: /data/db-project
        clone: true
    - name: Build database infra
      docker_compose:
        project_src: /data/db-project
        files: 
        - docker-compose.yaml

        









      
    
