- name: Create cron  to delete logs in vcn every 48 hours
  hosts: all_grpups
  become: true

  tasks:
    - name: Create cron job 
      ansible.builtin.cron:
        name: clear logs
        minute: 0
        hour: 0
        job: /usr/bin/find /data/backup/ -name 'sel-*' -mtime +5 -delete
        state: present
    - name: Grab the list of cron jobs
      shell: 'crontab -l'
      register: Command_output
    - debug:
        var: command_output.stdout_lines
