version: '3'
services:
  jenkins:
    container_name: jenkins-ansible
    image: jenkins
    build:
      context: jenkins-ansible
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    enviroment:
      - MYSQL_ROOT_PASSWORD="value1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
networks:
  net
