#!groovy
pipeline {
  agent any
  stages{
    stage('Collect artifacts')
      agent { label 'built-in'}
      steps{
        checkout scm
        stash 'Scripts'
    }
  }
  stage('Copy artifacts to the agent'){
    steps{ unstash 'Scripts' 
  }}
  stage( 'Build' ){
    agent { label 'built-in'}
    steps{
      echo 'Execute Ansible playbook'  
      ansiblePlaybook playbook: '/usr/local/bin/playbooks/windows_automation/main.yml', '/usr/local/bin/playbooks/windows_automation/inventory.ini'
    }
  }
  stage( 'Configure' ){
    agent { label 'windows'}
    steps{  
      echo 'Configuration script'  
      bat 'powershell C:/customization/ADDC.ps1'
}
}
