---
- name: Create a windows vm from template vm
  hosts: "{{ lookup('env','HOSTS') }}"
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Instant clone a VM with quest_customization
      vmware_guest:
        hostname: "{{ lookup('env','vcenter_hostname') }}"
        username: "{{ lookup('env','vcenter_username') }}"
        password: "{{ lookup('env','vcenter_password') }}"
        folder: "{{ lookup('env','folder') }}"
        datacenter: "{{ lookup('env','datacenter') }}"
        cluster: "{{ cluster }}"
        template:  "{{ lookup('env','template') }}"
        name:  "{{ lookup('env','vm_hostname') }}"
        disk:
           - size_gb: "{{ disk_size }}"
             type: "thin"
             autoselect_datastore: yes
        hardware:
          memory_mb: "{{ memory_mb }}"
          num_cpus: "{{ num_cpus }}"
        networks:
          - name: "{{ vlan_name }}"
            ip: "{{ ip_address }}"
            netmask: "{{ num_cpus }}"
            gateway: "{{ gateway }}"
            dns_servers:
            - "{{ dns1 }}"
            - "{{ dns2 }}"
           type: static
           connected: yes
           start_connected: yes
         wait_for_ip_address: yes
         cusctomization:
           autologon: yes
           autologoncount: 3
           dns_servers:
             - "{{ dns1 }}"
             - "{{ dns2 }}"
            domain: "{{ lookup('env','DOMAIN') }}"
            domainadmin: "{{ lookup('env','DOMAINADMIN') }}"
            domainadminpassword: "{{ lookup('env','DOMAINADMINPASSWORD') }}"
            hostname: "{{ lookup('env','vm_hostname') }}"
            password: "{{ lookup('env','local_admin_pass') }}"
            joindomain: "{{ lookup('env','DOMAIN') }}"
            runonce:
            - powershell.exe -ExecutionPolicy Unrestricted -File C:\customization\preConf.ps1
         wait_for-customization: yes
         validate_certs: false
       delegate_to: localhost  
