name: Docker Image CI

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub with credentials
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build the Docker image
      run: docker build app/dev/microservices/project01 --file app/dev/microservices/project01/Dockerfile --tag vkhomysh/web-001:v2
      
    - name: Push the Docker image to Docker Hub
      run: docker push vkhomysh/web-001:v2
